name: Deploy to Vercel 

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository Action
        uses: actions/checkout@v2

      - name: Install vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build app
        run: npm run build

      - name: Get Vercel Token
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Using Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Build to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}